### ISSUE TITLE
Kerberos Key List Attack not working

### ISSUE THREAD

**Issue by jsdhasfedssad** [fortra/impacket#1478]
Impacket version:  0.10.0
Python version:  3.10.9
Target OS:  Server 2019

I am trying to execute the various versions of the Kerberos Key List attack shown [here](https://www.secureauth.com/blog/the-kerberos-key-list-attack-the-return-of-the-read-only-domain-controllers/) but none of the attacks works for me. 

Below you can see examples of failed attacks, that the account domainadmin1 has privileged access to RODC1, that Kali can resolve DNS names properly and that port 88 is open on RODC1. What am I doing wrong?

<img width="704" alt="keylistattack1" src="https://user-images.githubusercontent.com/97032878/216285637-f9056894-a750-44dc-b9d2-e6eb1801ce44.png">

**Comment by 0xdeaddood** [comment]
Hi @jsdhasfedssad!

The first error, as is detailed in the output, is related to the name resolution system. It could have many causes (check your DNS configurations). In the meantime, try using the IP address of the Domain Controller instead of its domain name. 

In the second one, you forgot to use the `LIST` argument and the -`tf` flag for the file. Something like this should work:

`keylistattack.py -kdc DOMAIN_NAME -t TARGET_USER -rodcNo NUMBER -rodcKey KEY -tf FILE_NAME LIST`

Closing. Reopen if you need further help.
