### ISSUE TITLE
secretsdump.py error

### ISSUE THREAD

**Issue by NotSoEthical69** [fortra/impacket#1480]
help everytime i launch my command i got this error, how can i fix that ?

python secretsdump.py ATLAS.local/fcastle:Password1@192.168.45.170

**Impacket v0.10.0 - Copyright 2022 SecureAuth Corporation

[-] RemoteOperations failed: RemoteOperations.__init__() takes from 3 to 4 positional arguments but 5 were given
[-] NTDSHashes.__init__() got an unexpected keyword argument 'ldapFilter'
[*] Cleaning up...**

**Comment by Crypt0s** [comment]
Try re-installing impacket by cloning the impacket project, then from inside of the impacket directory, and then running

`python3 -m pip install .`

**Comment by 0xdeaddood** [comment]
Hi @NotSoEthical69!

This error is related to a version mismatch between the Impacket library and the `secretsdump.py` example. As @Crypt0s mentioned, try re-installing impacket.

Closing. Reopen if you need further help.

**Comment by Brucolac1** [comment]
I have the same issue. I reinstalled impacket, yet this issue remains. What else can I do?

**Comment by iAniket9** [comment]
I am facing the same issue as well. Re-installing does not see to resolve this issue.

**Comment by GoochMagooch** [comment]
└─$ python3 -m pip install .                                                                               
Defaulting to user installation because normal site-packages is not writeable
Processing /opt/impacket
  Preparing metadata (setup.py) ... done
Requirement already satisfied: charset_normalizer in /usr/lib/python3/dist-packages (from impacket==0.10.1.dev1) (3.0.1)
Requirement already satisfied: dsinternals in /usr/lib/python3/dist-packages (from impacket==0.10.1.dev1) (1.2.4)
Requirement already satisfied: flask>=1.0 in /usr/lib/python3/dist-packages (from impacket==0.10.1.dev1) (2.2.2)
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from impacket==0.10.1.dev1) (0.18.2)
Requirement already satisfied: ldap3!=2.5.0,!=2.5.2,!=2.6,>=2.5 in /usr/lib/python3/dist-packages (from impacket==0.10.1.dev1) (2.9.1)
Requirement already satisfied: ldapdomaindump>=0.9.0 in /usr/lib/python3/dist-packages (from impacket==0.10.1.dev1) (0.9.3)
Requirement already satisfied: pyOpenSSL>=21.0.0 in /usr/lib/python3/dist-packages (from impacket==0.10.1.dev1) (23.0.0)
Requirement already satisfied: pyasn1>=0.2.3 in /usr/lib/python3/dist-packages (from impacket==0.10.1.dev1) (0.4.8)
Requirement already satisfied: pycryptodomex in /usr/lib/python3/dist-packages (from impacket==0.10.1.dev1) (3.11.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from impacket==0.10.1.dev1) (1.16.0)
Building wheels for collected packages: impacket
  Building wheel for impacket (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      error: could not create 'build': Permission denied
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for impacket
  Running setup.py clean for impacket
Failed to build impacket
Installing collected packages: impacket
  Running setup.py install for impacket ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for impacket did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      running install
      /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      error: could not create 'build': Permission denied
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> impacket

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

This is the error I get when I perform the solution given above

**Comment by Crypt0s** [comment]
@GoochMagooch you're getting that error because your current user account doesn't have permissions to write to the impacket folder (which is your current working directory).

Maybe you cloned it with another user account?  Try changing the ownership of the folder to your current user account and re-trying.
