### ISSUE TITLE
Please add setuptools to setup.py / requirements.txt

### ISSUE THREAD

**Issue by rhertzog** [fortra/impacket#885]
In Debian, we have some dependencies which are automatically generated based on dependency data in setup.py and requirements.txt but we got bug report that we were lacking "pkg_resources".

Please document this dependency properly. Thank you!

**Comment by rhertzog** [comment]
Forget this pkg_resources is part of setuptools... it's just that Debian packages this separately. I'm not sure that you have anything to do really.

**Comment by rhertzog** [comment]
Thinking a bit more I believe it would make sense for you to document the dependency on setuptools in requirements.txt / setup.py. I have seen other projects do this.

**Comment by asolino** [comment]
Thanks for the feedback @rhertzog. Do you know what's the minimum required `setuptools` version? First time I'm hearing about this issue.

**Comment by rhertzog** [comment]
I don't think you need to specify a minimum required version. pkg_resources has been part of setuptools for a very long time, at least since version 0.6c in 2007.

**Comment by noraj** [comment]
https://bugs.archlinux.org/task/75432

> impacket actually requires python-setuptools at runtime. It's not listed in setup.py or requirements.txt but it's `import pkg_resources` (cf.[ https://github.com/SecureAuthCorp/impacket/blob/3c6713e309cae871d685fa443d3e21b7026a2155/impacket/version.py#L10](https://github.com/SecureAuthCorp/impacket/blob/3c6713e309cae871d685fa443d3e21b7026a2155/impacket/version.py#L10)) in `impacket/version.py`. So without setup tools it's triggering the following error
>
> ```
> ModuleNotFoundError: No module named 'pkg_resources'
> ```

Most people don't encouters this error because they already have python-setuptools installed on their system. But when you install the tool on a clean environment (new install, docker container, nspawn, etc.) you encounter the issue.

But as both `setup.py` and `requirements.txt` are deprecated now, I suggest following [PEP 517](https://peps.python.org/pep-0517/), [PEP 518](https://peps.python.org/pep-0518/), [621](https://peps.python.org/pep-0621/), [660](https://peps.python.org/pep-0660/) and move to the modern `pyproject.toml`.

Using `pyproject.toml` would allow the user or distro packager to either use [setuptools](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html), [pip](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/), [poetry](https://python-poetry.org/docs/pyproject/), [flit](https://flit.pypa.io/en/latest/pyproject_toml.html), etc.

**Comment by gabrielg5** [comment]
Closed in #1598
